name: 📚 Documentation
description: Suggest improvements or report issues with documentation
title: "[Docs]: "
labels: ["documentation", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve the M31 Autonomous documentation!
        
        Please provide specific details about the documentation issue or improvement.
  
  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation is this related to?
      options:
        - README
        - API Reference
        - User Guide
        - Tutorials
        - Code Comments
        - Website
        - Other
    validations:
      required: true
  
  - type: textarea
    id: current-state
    attributes:
      label: Current Documentation
      description: Please describe the current state of the documentation.
      placeholder: "The current documentation about X is missing/unclear/incorrect because..."
    validations:
      required: true
  
  - type: textarea
    id: proposed-changes
    attributes:
      label: Proposed Changes
      description: Describe what changes you would like to see.
      placeholder: "I suggest updating the documentation to explain..."
    validations:
      required: true
  
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Context
      description: Add any other context about the documentation issue here.
      placeholder: "This documentation is particularly important for new users who..."
    validations:
      required: false
  
  - type: input
    id: related-links
    attributes:
      label: Related Links
      description: Links to relevant documentation pages, if applicable
      placeholder: "https://m31lab.github.io/some-page"
    validations:
      required: false
  
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this documentation issue, you agree to follow our Code of Conduct.
      options:
        - label: I agree to follow the project's Code of Conduct
          required: true 